### ISSUE TITLE
Tracker as "Controller"

### ISSUE THREAD

**Issue by Hackebein** [jangxx/VRC-Tracked-Objects#2]
It would be nice to have an advanced mode where i can select trackers in "Controller" drop down.

**Comment by jangxx** [comment]
Added in version 0.2.0

**Comment by Sierra0525** [comment]
is this functionality still in? how do I enable it? thanks.

**Comment by jangxx** [comment]
You have to enable it in the config file (Default location: `%LOCALAPPDATA%\jangxx\VRC Tracked Objects\config.json`). There is a config key called `AllowAllDevices`, which, when set to `true`, will show all controllers and trackers in the controller dropdown.
